development:
  adapter: postgresql
  encoding: unicode
  database: vicini_development
  pool: 5
  username: vicini

test:
  adapter: postgresql
  encoding: unicode
  database: vicini_test
  pool: 5
  username: vicini
